### ISSUE TITLE
Bungee Connection issue Snapshot 270

### ISSUE THREAD

**Issue by devryb** [OpenMods/OpenModsLib#29]
We've noticed a weird issue with openmods build 270
When the client doesnt have the inventory tweaks mod installed they are able to move from one server to another on a bungee network fine, however when installing inventory tweaks an internal exception occurs.

Here is the client log when it fails to connect and has inventory tweaks installed:
http://pastebin.com/nLD98Zcs

Here it is when it's a successful connection without inventory tweaks:
http://pastebin.com/LJM40GQP

The only reason why I'm thinking its an issue with open mods at this point is the extra logging there on the successful connection.  If this should be reported elsewhere let me know.

**Comment by devryb** [comment]
Ok nevermind I think there is an issue with this here.  This is now with Snapshot 280 when connecting to a server on a bungeecord network there is nothing in the server log and only this in the client log.

[21:09:09] [Netty Client IO #2/INFO] [OpenMods]: openmods.network.IdSyncManager.onDisconnect(IdSyncManager.java:124): Disconnected, restoring local data

The connection to the server times out

**Comment by devryb** [comment]
Ok getting this in the server log
[21:18:32] [Server thread/INFO]: openmods.OpenModsClassTransformer.tryApplyContextWrapper(OpenModsClassTransformer.java:246): Adding context wrappers to mx(net.minecraft.server.management.ItemInWorldManager)

**Comment by devryb** [comment]
I have confirmed running without bungeecord fixes this issue so this mod is not compatible with bungeecord...

**Comment by boq** [comment]
Sorry, posting random lines isn't going to  help. None of the logs you included are actually containing anything abnormal. There is nothing wrong with OpenBlocks on client side. Maybe you should direct your attention to server or proxy?

Closing for now, until you can provide more info. We worked on bungee compatibility in scope of OpenMods/OpenBlocks#498 and have confirmation it works.

**Comment by boq** [comment]
From other issue:
>It was a corrupted or different then the server open mods config file on the client.

Any more details? Particular combination of options or just malformed file?

**Comment by devryb** [comment]
I'll pastebin both working and not working set when I get home.

**Comment by devryb** [comment]
Ok when I download a fresh copy of the modpack in question it's no longer an issue.. Even though when I was trying to get this working thats what I did about 3 times then.  Since I don't have a not working set of configs now this can be closed (Already is)
If I come across this particular issue again I'll be sure to save a copy of the configs I have problems with.
