### ISSUE TITLE
OpenModsLib crashing Forge Server

### ISSUE THREAD

**Issue by StuardBr** [OpenMods/OpenModsLib#34]
Hello! i'm having a crash when a start a server with the OpenModsLib.

Crash: http://pastebin.com/n46YBgVG

Versions:
OpenModsLib: 0.6-snapshot-295.jar and 0.6-snapshot-300.jar
Forge Version: 10.13.2.1263 

On client is working, the crash is only on server.

Thanks for the atention :)

**Comment by boq** [comment]
I'm unable to reproduce and I have almost no idea what triggers this bug. There was some room to improvement, but I can't confirm fix, Please reopen if persist with recent snapshot.

**Comment by StuardBr** [comment]
Hello! Tks for the fast repply. 
Updated to snapshot-301 and still crashing, but another error: http://pastebin.com/ESzxv4kZ

Tks again :)

**Comment by boq** [comment]
That's basically same as #27 and #28 - you are keeping something weird in mods folder or even modifying `minecraft.jar`.

**Comment by StuardBr** [comment]
Yes yes, i tried withou the other mods and the serer starts ok. I will add one by one to see if it's a incopatibilty and i'll post here again. Tks again :)
