### ISSUE TITLE
Crash w/ Thermal Dynamics

### ISSUE THREAD

**Issue by Gideonseymour** [OpenMods/OpenModsLib#44]
I'm experiencing a crash when connecting a Thermal Dynamics itemduct with a servo to an Almagator from Modern Alchemy. It occured when I clicked the Redstone tab, and now the world does not load.

I'm not certain if it's a problem with the mod itself or OpenMods, but I figured I would report it in both places just in case. Using OpenModsLib 0.6 Snapshot 323 and Openblocks 571.
http://paste.feed-the-beast.com/view/dea3e7d7

Link to Modern Alchemy for reference: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2374284-modern-alchemy-creating-items-with-lightning-and

**Comment by boq** [comment]
Looks like ModernAlchemy problem: last parameter (inventory size) [here](https://github.com/TeamBR-Modding/ModernAlchemy/blob/Trying-out-openmods/src/main/java/com/dyonovan/modernalchemy/common/tileentity/machines/TileAmalgamator.java#L69) should be 2.

I can probably add some code to prevent that from happening.

**Comment by pauljoda** [comment]
Hi. I'm a developer from Modern Alchemy. We haven't been working on this mod as much lately as we are working on a 1.8 mod. I'll jump back in there and fix that on our end as well. Thanks for added support on your end.
