### ISSUE TITLE
Curse Version Errors

### ISSUE THREAD

**Issue by Daphonic** [OpenMods/OpenModsLib#55]
I'm getting OpenperipheralAddons requires Openmods 0.8,0.9 i try and install that on Curse, and wont work? Is it because the jar is OpenModsLib?

**Comment by boq** [comment]
Well, I suggest doing exactly as bug says and download OpenModsLib 0.8, either from Curse or from [here](http://openmods.info).

**Comment by Daphonic** [comment]
I have. I still get the error. I'm using the both updated curse versions.

**Comment by boq** [comment]
Here are MD5 hashes and sizes of latest versions I have uploaded to Curse and on our page. I've checked before uploading (an re-checked just moments ago) that they all load together. Can't help you any further.

```
f2d40d48f47df5684b459c863fe078cb 400146 OpenPeripheralAddons-1.7.10-0.4.jar
5540f0205e7766bf6310b4ac7b055018 250607 OpenPeripheralIntegration-1.7.10-0.3.jar
fd4dd67ac7c85d44ad3c5aa08f052dc1 384220 OpenPeripheralCore-1.7.10-1.2.jar
3197b23ed673022dfc26574e59d89f62 862338 OpenModsLib-1.7.10-0.8.jar
5c439e4a90771678a203efe9b9bef7b9 2655332 OpenBlocks-1.7.10-1.4.4.jar
```
