### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dream-Master** [OpenMods/OpenModsLib#58]
I get this Crash with the newest Open Mods lib version 405.

Crashlog:
https://gist.github.com/Dream-Master/5239f236f1279edf1cd0#file-openmodslib

**Comment by boq** [comment]
Expected. I'm currently in middle of rewriting part of code. Also OpenMods/OpenBlocks#722.

Also, not "version". Snapshot. Only official releases are guaranteed to work.

**Comment by Dream-Master** [comment]
It is not a complain only a crash i post.
