### ISSUE TITLE
Crash with Config

### ISSUE THREAD

**Issue by Yanniclord** [OpenMods/OpenModsLib#59]
Having problems when starting a fresh server world. I had this issue before, and could resolve it, but this time it does not work, so i would like to know what causes it.

Log: http://pastebin.com/mNZa5e7n

**Comment by boq** [comment]
This again... #27, #28, #34, #39 etc.

I have no idea why this happens, but I last time I got report about it, it was fixed by removing liteloader from server.

**Comment by Yanniclord** [comment]
Ah ok lets see if that fixes it, i think it might be the problem. The last time i removed something else. I report back in some seconds.

**Comment by Yanniclord** [comment]
I can give you a list of the mods i am currently using, if you know wich one it is that would be good :)

**Comment by Yanniclord** [comment]
And no it did not fix it, its most likely another client side mod on the server or so. https://docs.google.com/spreadsheets/d/1pl0CRzaulUByRIeLfaWJ0sNTkpkOvxTXr1MWe25BGVA/edit#gid=0

**Comment by Yanniclord** [comment]
Here the FTP list: 
![unbenannt](https://cloud.githubusercontent.com/assets/5807595/10871058/840cca6a-80dc-11e5-974f-99f49e86f6f2.PNG)

![unbenannt2](https://cloud.githubusercontent.com/assets/5807595/10871059/86cd1822-80dc-11e5-987f-cae3310d06b7.PNG)

**Comment by Yanniclord** [comment]
Ok i think i am getting it to work. I report back soon.

**Comment by Yanniclord** [comment]
Ok i forgot to switch back to Forge 1448, and then it worked. Also i of course removed LiteLoader and some other client mods.
