### ISSUE TITLE
"missing coremod OpenMods [0.7.1,0.8}"

### ISSUE THREAD

**Issue by WilkerS1** [OpenMods/OpenModsLib#60]
This image here is about the error http://i.imgur.com/ywgpmR2.png

![Missing coremod](http://i.imgur.com/ywgpmR2.png)
i alreday tried to update the OpenModsLib, but the problem persists

**Comment by boq** [comment]
One of the mods needs OLD version of OpenModsLib. `[0.7.1,0.8)` means 0.7.1 or older, but not 0.8 and older (and no, we can't make more descriptive notation since a) it's FML thing and b) it's widely accepted notation for open ranges).

Update all mods to current version.

**Comment by WilkerS1** [comment]
is there a way to know what mod is requiring an old version of the libary?

**Comment by boq** [comment]
Should be somewhere in console/logs.

**Comment by WilkerS1** [comment]
Thanks :)
