### ISSUE TITLE
[1.10.2] Bucket Fill Crash

### ISSUE THREAD

**Issue by WhiteWidow** [OpenMods/OpenModsLib#66]
Crash after try to fill bucket.
Crash - https://pastebin.com/TDm2SMDq

[spongeforge-1.10.2-2281-5.2.0-BETA-2418]
[Forge -12.18.3.2281]

**Comment by boq** [comment]
#64 duplicate. tl;dr: I know about it, keeping it in there to prevent mass use of unfinished builds.

**Comment by boq** [comment]
Keeping it open it prevent duplicates.

**Comment by essem2** [comment]
any ETA on this bug? its a simple NPE at https://github.com/OpenMods/OpenModsLib/blob/1.10.X/src/main/java/openmods/liquids/BucketFillHandler.java#L62 and occurs when target is null (a little bit too far away)

**Comment by boq** [comment]
It's last thing I will fix before I release alpha. TODO list is getting shorter, but is still far from empty.
