### ISSUE TITLE
[1.10.2] WorldUtils.getWorld seems to try to get the client world when running on a server

### ISSUE THREAD

**Issue by apemanzilla** [OpenMods/OpenModsLib#68]
I haven't had much time to do more testing, but it seems that `WorldUtils.getWorld` attempts to get the client world when it should be getting the server world - I found it when getting disconnected while trying to set the outputs of a vacuum hopper on a server. I made a temporary fix for the server only (just remove the conditional and always get the server world) but I figured you should know about it.

[Here](https://hastebin.com/unurikazup.rb)'s the stack trace from the server after trying to assign a vacuum hopper output.

**Comment by boq** [comment]
This function was supposed to handle both client and servers, but wasn't reliable enough.

**Comment by apemanzilla** [comment]
Thanks!
