### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by Driphosting** [OpenMods/OpenModsLib#69]
Dear creators,
First off all i'm not sure if this can run on tekkit yes or no but i would like to know.
I tried it on tekkit lite to day with a negative result. it gave a crash because it couldn't find (OpenModsCore).
https://pastebin.com/Gx60c5Tw here is the crash report if needed and i hope someone can help me out on this.

greets,
Joris

**Comment by boq** [comment]
It should work with any launcher, unless they do something nasty.

Basically, OpenModsCore is coremod contained in OpenModsLib-1.7.10-0.10.jar. So either this is issue with non-standard launcher (shouldn't be) or jar file was modified.

**Comment by Driphosting** [comment]
Can it be that the minecraft version (1.4.7) is not compatible? 
We run tekkit lite server and the jar is downloaded straight from openmod.

**Comment by boq** [comment]
Uhhhh, yup, that's probably it. I can't help you there, as first OpenBlocks that ever existed was for 1.5.
