### ISSUE TITLE
/tmp/mc_libs/0/calc-0.2.jar (Permission denied)

### ISSUE THREAD

**Issue by meteovio** [OpenMods/OpenModsLib#71]
Hi,

After a long search, I've been unable to find a solution hence my message here, and I apologise bothering you with this issue, but I have a similar problem as this guy 
->https://github.com/OpenMods/OpenModsLib/issues/70

My modpack is hosted online by some company and they don't allow writing in /tmp (for.. some reasons) and they seem to be pretty strict about this as the support does not offer any alternative (not even using **java -Djava.io.tmpdir=/path/to/tmpdir** which could potentially fix the issue, thanks to this german-translated [thread](https://board.nitrado.net/support-de-german-only/support-gameserver/minecraft/weitere-modpacks-modifikationen/123211/twitch-launcher-forge-server-mit-sink-into-madness-l-uft-lokal-aber-1-1-auf-nitrado-nicht/))

I was wondering if it was possible rolling a version of the mod, that doesn't behave this way? I like OpenBlocks and I wish to use it but the way it works with the libraries makes it incompatible with some hosting company. Let me know if you could look into this!

Thanks

**Comment by Shiz0id** [comment]
I've had the same issue, in the end I just removed the mod from the pack, since my hosting company wouldn't change the permissions for the /tmp directory

**Comment by boq** [comment]
Ehh, I'm probably going to drop that functionality in next release.

**Comment by boq** [comment]
Reverted to safer method in latest snapshots.
