### ISSUE TITLE
Client Crash while loading

### ISSUE THREAD

**Issue by cmleininger** [OpenMods/OpenModsLib#73]
Installed Open Blocks along with OpenModsLib on top of a lightly modded Vanilla Forge, and the client crashed while loading. I then tried again with ONLY Open Blocks and OpenModsLib on top of Vanilla Forge (version 1.2.1, forge version 14.23.0.24.86) and got the same crash. My crash log is attached.
[crash-2017-12-17_13.54.35-client.txt](https://github.com/OpenMods/OpenModsLib/files/1566069/crash-2017-12-17_13.54.35-client.txt)

**Comment by boq** [comment]
It requires recent-ish Forge (latest recommended should be fine). Is there any particular reason you are using 2486?

**Comment by cmleininger** [comment]
That's just what the Vanilla Forge modpack is using. I could try updating and see what happens, but I haven't done so yet because I figured there was a reason the modpack hadn't updated yet?

**Comment by boq** [comment]
Ok. Anyway, latest update depends on few features, so can't fix that on my side.
