### ISSUE TITLE
OpenLib causing Minecraft not to launch

### ISSUE THREAD

**Issue by Eragoneq** [OpenMods/OpenModsLib#74]
OpenLib causes Minecraft not to launch at all. Idk if it's caused because of any other mods, but it doesn't seem to.
Issue: [https://pastebin.com/SjEBuATc](https://pastebin.com/SjEBuATc)
Whole log: [https://pastebin.com/0hYVzRa6](https://pastebin.com/0hYVzRa6)
Probably similar to this one: #72

**Comment by boq** [comment]
Nah, but it's very similar to this one: https://github.com/OpenMods/OpenBlocks/issues/864.

**Comment by Eragoneq** [comment]
Ok, you'r right, but that means that you've got wrong link on curse page.
[https://minecraft.curseforge.com/projects/openmodslib/files/2510771](url)
It says that it's for 1.12.2, but it downloads 1.11.2 version

**Comment by Eragoneq** [comment]
Ok, but that means that you have wrong file linked on the curse page.
[https://minecraft.curseforge.com/projects/openmodslib/files/2510771](url)
It says it's for 1.12.2, but it downloads the 1.11.2 version.
