### ISSUE TITLE
"Can't use a null-name for the registry, object null."

### ISSUE THREAD

**Issue by Peekofwar** [OpenMods/OpenModsLib#77]
So, I loaded a few 1.12.2 mods, and I then proceeded to launch Minecraft. The game then crashed on load.

[crash-2018-01-15_10.43.54-client.txt](https://github.com/OpenMods/OpenModsLib/files/1632201/crash-2018-01-15_10.43.54-client.txt)

**Comment by boq** [comment]
Not OpenMods:
```
mekanism.tools.common.ToolsItems.registerItems(ToolsItems.java:216) 	at mekanism.tools.common.MekanismTools.registerItems(MekanismTools.java:79)
```
