### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Hyperleogamer** [OpenMods/OpenModsLib#79]
So when i get on the game it will go after openmodslib and go to openblocks then crash for something about this mod please help

**Comment by Hyperleogamer** [comment]
Also yes i did try doing other things

**Comment by boq** [comment]
Apparently, "other things" don't include posting of actual crash report.

**Comment by Hyperleogamer** [comment]
by other things i mean stuff like downloading a new version and puting other mods away

**Comment by boq** [comment]
Let me say that straight: I can't diagnose crash if you don't post crash report.
