### ISSUE TITLE
Requires 0.11.5 or above and below 0.12 (you have 0.12) wow.

### ISSUE THREAD

**Issue by CallumlousTV** [OpenMods/OpenModsLib#80]
![image](https://user-images.githubusercontent.com/45427259/49155259-65f02d00-f312-11e8-8cdd-a372739365b6.png)
i can't use one of my mods

**Comment by CallumlousTV** [comment]
downgraded and it crashes my game,
crash report: https://pastebin.com/rph3q80R

**Comment by boq** [comment]
"Adding OpenModsLib-**1.10.2**-0.11.5.jar to the mod list"

OpenBlocks 1.8 goes with OpenModsLibs 0.12, so rather then downgrading one, update another.
