### ISSUE TITLE
Grave not spawning in multiplayer

### ISSUE THREAD

**Issue by rk-exxec** [OpenMods/OpenModsLib#86]
Logfile: https://pastebin.com/E1Yb1aFx
`Grave drops event cancelled`
Somehow the grave of my buddy spawned, but mine did not.
Minecraft version 1.12.2

**Comment by boq** [comment]
Exception seems to be coming from `ovh.corail.tombstone.event.EventHandler.onPlayerDrops` please report it for that mod.
