### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by ghost** [OpenMods/OpenModsLib#90]
Hello my problem is that this mod as soon as you start a 1.7.10 server, it crashes in the start phase with the error that the OpenModsLib.json file cannot be read.
[fml-server-latest.log](https://github.com/OpenMods/OpenModsLib/files/8755541/fml-server-latest.log)

**Comment by boq** [comment]
Looks like duplicate of https://github.com/OpenMods/OpenModsLib/issues/27.
Also, 1.7.10 is unsupported.
